export default {
  "audios": [{
    "id": 1,
    "name": "aguirre",
    "quote": "esabsolutamentefalso"
  }, {
    "id": 2,
    "name": "aguirre",
    "quote": "francosocialista"
  }, {
    "id": 3,
    "name": "aguirre",
    "quote": "recorteslosquehizozapatero"
  }, {
    "id": 4,
    "name": "anabotella",
    "quote": "dosmanzanas"
  }, {
    "id": 5,
    "name": "anabotella",
    "quote": "relaxincafe"
  }, {
    "id": 6,
    "name": "anabotella",
    "quote": "sisesumandosmanzanas"
  }, {
    "id": 7,
    "name": "aznar",
    "quote": "ayerporlanoche"
  }, {
    "id": 8,
    "name": "aznar",
    "quote": "elregimeniraqui"
  }, {
    "id": 9,
    "name": "aznar",
    "quote": "espanavabien"
  }, {
    "id": 10,
    "name": "aznar",
    "quote": "estamostrabajandoenello"
  }, {
    "id": 11,
    "name": "aznar",
    "quote": "hablandocatalan"
  }, {
    "id": 12,
    "name": "aznar",
    "quote": "yquienteadichoati"
  }, {
    "id": 13,
    "name": "barcenas",
    "quote": "condoscontresocuatro"
  }, {
    "id": 14,
    "name": "barcenas",
    "quote": "meparecekafkeano"
  }, {
    "id": 15,
    "name": "barcenas",
    "quote": "noserespeto"
  }, {
    "id": 16,
    "name": "barcenas",
    "quote": "novoyadeclararnada"
  }, {
    "id": 17,
    "name": "barcenas",
    "quote": "siexistenihaexistido"
  }, {
    "id": 18,
    "name": "barcenas",
    "quote": "todoesunaburdamanipulacion"
  }, {
    "id": 19,
    "name": "anabotella",
    "quote": "dosmanzanas"
  }, {
    "id": 20,
    "name": "camps",
    "quote": "claroquemepagomistrajes"
  }, {
    "id": 21,
    "name": "camps",
    "quote": "durantemuchosanosno"
  }, {
    "id": 22,
    "name": "camps",
    "quote": "feliznavidad"
  }, {
    "id": 23,
    "name": "camps",
    "quote": "gustariaverenunacuneta"
  }, {
    "id": 24,
    "name": "camps",
    "quote": "hoyestoymuyfeliz"
  }, {
    "id": 25,
    "name": "camps",
    "quote": "nadaabsolutamentenadaqueocultar"
  }, {
    "id": 26,
    "name": "camps",
    "quote": "profundamenteindignado"
  }, {
    "id": 27,
    "name": "camps",
    "quote": "teniamuchasganasdecontar"
  }, {
    "id": 28,
    "name": "camps",
    "quote": "unapartedeespana"
  }, {
    "id": 29,
    "name": "cospedal",
    "quote": "nadadesubirlosimpuestos"
  }, {
    "id": 30,
    "name": "cospedal",
    "quote": "chantajedenadie"
  }, {
    "id": 31,
    "name": "cospedal",
    "quote": "enpartesdiferido"
  }, {
    "id": 32,
    "name": "cospedal",
    "quote": "esunpartidodondequienlahace"
  }, {
    "id": 33,
    "name": "cospedal",
    "quote": "granpartidoquedefiende"
  }, {
    "id": 34,
    "name": "cospedal",
    "quote": "indemnizacionendiferido"
  }, {
    "id": 35,
    "name": "cospedal",
    "quote": "sablazosubidaiva"
  }, {
    "id": 36,
    "name": "cospedal",
    "quote": "vamosabajarlosimpuestos"
  }, {
    "id": 37,
    "name": "aguirre",
    "quote": "alhijoputa"
  }, {
    "id": 38,
    "name": "fabra",
    "quote": "aeropuertoparalaspersonas"
  }, {
    "id": 39,
    "name": "fabra",
    "quote": "aeropuertosinaviones"
  }, {
    "id": 40,
    "name": "fabra",
    "quote": "ciudadanosdelaprovincia"
  }, {
    "id": 41,
    "name": "fabra",
    "quote": "presientoqueeselmomento"
  }, {
    "id": 42,
    "name": "fabra",
    "quote": "sequenohoyelmejorpadre"
  }, {
    "id": 43,
    "name": "montoro",
    "quote": "nomassubidasdeimpuestos"
  }, {
    "id": 44,
    "name": "rajoy",
    "quote": "ahoravaasubireliva"
  }, {
    "id": 45,
    "name": "rajoy",
    "quote": "aquihayunpresidentequenosevaaesconder"
  }, {
    "id": 46,
    "name": "rajoy",
    "quote": "chiringuitos"
  }, {
    "id": 47,
    "name": "rajoy",
    "quote": "elivalopagantodoslosespanoles"
  }, {
    "id": 48,
    "name": "rajoy",
    "quote": "esaninaeslaqueestaen"
  }, {
    "id": 49,
    "name": "rajoy",
    "quote": "etaesunagrannacion"
  }, {
    "id": 50,
    "name": "rajoy",
    "quote": "findelacita"
  }, {
    "id": 51,
    "name": "rajoy",
    "quote": "ganobastantemas"
  }, {
    "id": 52,
    "name": "rajoy",
    "quote": "lasubidadelivaeselsablazo"
  }, {
    "id": 53,
    "name": "rajoy",
    "quote": "levaasubirelivaaestenino"
  }, {
    "id": 54,
    "name": "rajoy",
    "quote": "loschuches"
  }, {
    "id": 55,
    "name": "rajoy",
    "quote": "miromicuentaalfinaldemes"
  }, {
    "id": 56,
    "name": "rajoy",
    "quote": "modeloeducativocomodios"
  }, {
    "id": 57,
    "name": "rajoy",
    "quote": "noesciertosalvo"
  }, {
    "id": 58,
    "name": "rajoy",
    "quote": "nomevoyadeclararculpable"
  }, {
    "id": 59,
    "name": "rajoy",
    "quote": "nosepuedensubirlosimpuestos"
  }, {
    "id": 60,
    "name": "rajoy",
    "quote": "nosparecemallasubidadeliva"
  }, {
    "id": 61,
    "name": "rajoy",
    "quote": "nuncaerecibidodineronegro"
  }, {
    "id": 62,
    "name": "rajoy",
    "quote": "responderedeformaclaramp3"
  }, {
    "id": 63,
    "name": "rajoy",
    "quote": "seremoscontrasubidaimpuestos"
  }, {
    "id": 64,
    "name": "rajoy",
    "quote": "soysospechosodemuchascosas"
  }, {
    "id": 65,
    "name": "rajoy",
    "quote": "tengolosproblemasquetienen"
  }, {
    "id": 66,
    "name": "rajoy",
    "quote": "vivaelvino"
  }, {
    "id": 67,
    "name": "rajoy",
    "quote": "ylosciudadanossoncondenados"
  }, {
    "id": 68,
    "name": "rajoy",
    "quote": "yotrabajoparaquetodoelmundo"
  }, {
    "id": 69,
    "name": "rey",
    "quote": "lajusticiaesigualparatodos"
  }, {
    "id": 70,
    "name": "rey",
    "quote": "losientomuchomeeequivocado"
  }, {
    "id": 71,
    "name": "rey",
    "quote": "yporquenotecallas"
  }, {
    "id": 72,
    "name": "rita",
    "quote": "comprendoquesumujer"
  }, {
    "id": 73,
    "name": "rita",
    "quote": "incopetenteignorante"
  }, {
    "id": 74,
    "name": "rita",
    "quote": "nosevaasalirderositas"
  }, {
    "id": 75,
    "name": "rita",
    "quote": "quecierrelapuerta"
  }, {
    "id": 76,
    "name": "rita",
    "quote": "zapateromultiplicateporcero"
  }, {
    "id": 77,
    "name": "rubalcaba",
    "quote": "ungobiernoquenolesmienta"
  }, {
    "id": 78,
    "name": "santamaria",
    "quote": "estegobiernoseveobligado"
  }, {
    "id": 79,
    "name": "santamaria",
    "quote": "unrecargotemporalsolidaridad"
  }, {
    "id": 80,
    "name": "vega",
    "quote": "noseaplanteadotocar"
  }, {
    "id": 81,
    "name": "zp",
    "quote": "championleague"
  }, {
    "id": 82,
    "name": "zp",
    "quote": "noestamosenunacrisiseconomica"
  }, {
    "id": 83,
    "name": "zp",
    "quote": "sistemamassolido"
  }, {
    "id": 84,
    "name": "zp",
    "quote": "buenasnochesybuenasuerte"
  }, {
    "id": 85,
    "name": "zp",
    "quote": "estaremuycerca"
  }, {
    "id": 86,
    "name": "zp",
    "quote": "paraestimularapoyarfollar"
  }, {
    "id": 87,
    "name": "zp",
    "quote": "suspenderpara2011"
  }]
}